source( paste0( dt$R, "/R/wd.R" ) )
source( paste0( wd$scripts, "packages_read.R" ) )
source( paste0( wd$scripts, "_function_global.R" ) )
source( paste0( wd$scripts, "_function_read_service_backup_path.R" ) )
source( paste0( wd$scripts, "_function_read_sql_path.R" ) )
source( paste0( wd$scripts, "_function_read_produktnummer.R" ) )
source( paste0( wd$scripts, "_function_z_xaxisdate.R" ) )
source( paste0( wd$scripts, "_function_read_LG_clean_prediction.R" ) )
source( paste0( wd$scripts, "_function_plot_matplot_pchplot.R" ) )
source( paste0( wd$scripts, "_function_match_Lab_LG.R" ) )
source( paste0( wd$scripts, "dt_entertainment.R" ) )
source( paste0( wd$scripts, "_function_read_LG3_status.R" ) )
source( paste0( wd$scripts, "_function_fingerprint.R" ) )

source( paste0( wd$scripts, "_function_pca_plotpara.R" ) )

source( paste0( wd$scripts, "_function_val_drk.R" ) )
source( paste0( wd$scripts, "_function_val_ref.R" ) )
source( paste0( wd$scripts, "_function_val_spc.R" ) )
source( paste0( wd$scripts, "_function_val_spc.R" ) )
source( paste0( wd$scripts, "_function_val_col_range.R" ) )

source( paste0( wd$scripts, "_function_read_LG3_csv.R" ) )
source( paste0( wd$scripts, "_function_read_LG2_csv.R" ) )
source( paste0( wd$scripts, "_function_read_SG_csv.R" ) )
source( paste0( wd$scripts, "_function_read_product.R" ) )
source( paste0( wd$scripts, "_function_unzip_LG2.R" ) )
source( paste0( wd$scripts, "_function_read_LG_csv.R" ) )
source( paste0( wd$scripts, "_function_write_LG3_update_to_server.R" ) )

source( paste0( wd$scripts, "_function_model_keepout.R" ) )

source( paste0( wd$scripts, "_function_pls_wl.R" ) )

source( paste0( wd$scripts, "_function_read_mtx.R" ) )
